### ISSUE TITLE
TaskCommandLineEventArgs not getting ignored properly

### ISSUE THREAD

**Issue by nmbro** [JetBrains/TeamCity.MSBuild.Logger#12]
I noticed when using this msbuild logger that all of my csc.exe messages were bleeding through even though the Verbosity was minimal.

So I looked into the consolelogger implementation for msbuild and spotted the culprit:
https://github.com/dotnet/msbuild/blob/5c3e613314e4d5fcef0b90be3fe931db2e5a6128/src/Build/Logging/ParallelLogger/ParallelConsoleLogger.cs#L1061-L1067

Could be related to #10 but I'm not sure.

I have a fix ready in #11

**Comment by NikolayPianikov** [comment]
@nmbro Thank you for the very detailed description and your PR. I've done the same but quite a bit simpler.
FYI: And I've added the "Contribution" part to the readme file.
