### ISSUE TITLE
Parent FlowId Parameter

### ISSUE THREAD

**Issue by mblumenauer** [JetBrains/TeamCity.MSBuild.Logger#13]
I want to use the MsBuildLogger inside my Cake Build Script to get a nice collapsible Build Log in TeamCity.
Every Cake Task gets displayed in a seperate Service Message Block. But the MsBuild Output is not displayed inside these Blocks.
I figured it must be because the first Service Message from MsBuild doesnt have a flow parent.

`##teamcity[message text='Build started 26.05.2021 16:04:05.' status='NORMAL' tc:tags='tc:parseServiceMessagesInside' timestamp='2021-05-26T14:04:05.016+0000' flowId='433365ecaf9a4342b71e50126e2e2016']`

So i would like to set my Message Block as the flow parent but there is no Parameter to set the parent flow id for the messages generated by the MsBuildLogger.

Or is there another way to get my TeamCity log correctly structured?

**Comment by NikolayPianikov** [comment]
Unfortunately, it is not possible now

**Comment by NikolayPianikov** [comment]
To specify root flow-id use the environment variable _TEAMCITY_PROCESS_FLOW_ID_

**Comment by NikolayPianikov** [comment]
@mblumenauer please try [this package](https://www.nuget.org/packages/TeamCity.Dotnet.Integration/1.0.14-beta134)
