### ISSUE TITLE
There is no way to set ShowCommandLine to false

### ISSUE THREAD

**Issue by ltrzesniewski** [JetBrains/TeamCity.MSBuild.Logger#9]
`Parameters.ShowCommandLine` is a `bool?` property which is always either `null` or `true` when set with the `ShowCommandLine` option, but these two values have the same effect due to this code:

https://github.com/JetBrains/teamcity-msbuild-logger/blob/2e7012526dd39e6ed14d076f48bc3a5fdfaf1567/TeamCity.MSBuild.Logger/EventHandlers/MessageHandler.cs#L42-L45

This `if` can only be entered when `ShowCommandLine` is `false`, but there is no way to set it to this value.

This means that command lines are currently always logged. This is an issue when ReadyToRun compilation is enabled, as the crossgen command lines flood the log.

It looks like `ShowCommandLine` should be a `bool` property with a default value of `false` instead.

**Comment by NikolayPianikov** [comment]
@ltrzesniewski Thanks, I finally got it fixed 😄 there https://github.com/JetBrains/teamcity-msbuild-logger/issues/12
